PROFILE_SCANS="--all --plugins"
REMOTE_ACCESS_SEVERITY="CRITICAL"
UNSIGNED_APP_SEVERITY="CRITICAL"
SIP_DISABLED_SEVERITY="CRITICAL"
CHECK_HOMEBREW_OUTDATED=true
CHECK_MACOS_UPDATES=true
CHECK_UNSIGNED_APPS=true
CHECK_QUARANTINE_APPS=true
