# Mac Security Center default configuration.

STRICT_ON_WARNINGS=true
MAX_WORLD_WRITABLE_RESULTS=50
CHECK_DOCKER=true
CHECK_HOMEBREW=true
CHECK_HOMEBREW_OUTDATED=false
CHECK_MACOS_UPDATES=false
CHECK_UNSIGNED_APPS=false
CHECK_QUARANTINE_APPS=false
CRITICAL_ON_SIP_DISABLED=true
WARNING_ON_SSH_ENABLED=true
